import type { Metadata } from "next";
import localFont from "next/font/local";
import { Noto_Sans_JP } from "next/font/google"; //NotoSansJPフォントに統一
import { cn } from "@/lib/utils"; //utilsのcn関数をインポート
import "./globals.css";

const fontNotoSansJP = Noto_Sans_JP({ subsets: ["latin"] }); //NotoSansJPフォントに統一

export const metadata: Metadata = {
  title: "My WEB", //タイトルのメタデータを変更
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={cn(
          "bg-background antialiased min-h-screen",
          fontNotoSansJP.className //NotoSansJPフォントに統一
        )}
      >
        {children}
      </body>
    </html>
  );
}